#!/usr/bin/env bash
# Description: Test the open-remote plugin
set -e

PATH_OF_THIS_FILE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PLUGIN_PATH="$PATH_OF_THIS_FILE/open-remote.lua"

function unit_tests() {
	nvim -u NONE +"source $PLUGIN_PATH" +"lua Open_Remote_Test()"
}

function e2e_test_1() {
	printf "\ne2e_test_1\n"
	function setup_e2e_test(){
		local tmp_dir=$(mktemp -d)
		echo "running in: $tmp_dir"
		cd $tmp_dir
		sl init --git .
		printf 'hello\nworld\ndufus' > foo.txt
		sl add foo.txt
		sl commit -m lol
		sl paths --add default ssh://git@github.com/testuser/testrepo.git
		sl debugremotebookmark main .
	}
	setup_e2e_test
	nvim -u NONE foo.txt -Vvim.log +"source $PLUGIN_PATH" +2 +"OpenRemoteTestE2e"
}

function test_commit_with_multiple_bookmarks() {
	printf "\ntest_commit_with_multiple_bookmarks\n"
	function setup_e2e_test(){
		local tmp_dir=$(mktemp -d)
		echo "running in: $tmp_dir"
		cd $tmp_dir
		sl init --git .
		printf 'hello\nworld\ndufus' > foo.txt
		sl add foo.txt
		sl commit -m lol
		sl paths --add upstream ssh://git@github.com/upstream_repo/testrepo.git
		sl debugremotebookmark upstreammain .
		sl paths --add default ssh://git@github.com/testuser/testrepo.git
		sl debugremotebookmark main .
	}
	setup_e2e_test
	nvim -u NONE foo.txt -Vvim.log +"source $PLUGIN_PATH" +2 +"OpenRemoteTestE2e"
}

function test_with_repo_thats_not_cwd() {
	printf "\ntest_with_repo_thats_not_cwd\n"
	local tmp_dir_1=$(mktemp -d)
	local tmp_dir_2=$(mktemp -d)
	function setup_e2e_test(){
		# make repo without vcs
		echo "running in: $tmp_dir_1"
		cd $tmp_dir_1

		# make repo with vcs
		echo "running in: $tmp_dir_2"
		cd $tmp_dir_2
		sl init --git .
		printf 'hello\nworld\ndufus' > foo.txt
		sl add foo.txt
		sl commit -m lol
		sl paths --add default ssh://git@github.com/testuser/testrepo.git
		sl debugremotebookmark main .

		cd $tmp_dir_1
	}
	setup_e2e_test
	nvim -u NONE $tmp_dir_2/foo.txt -Vvim.log +"source $PLUGIN_PATH" +2 +"OpenRemoteTestE2e"
}

function e2e_test_2() {
	printf "\ne2e_test_2\n"
	function setup_e2e_test(){
		local tmp_dir=$(mktemp -d)
		echo "running in: $tmp_dir"
		cd $tmp_dir
		sl init --git .
		printf 'hello\nworld\ndufus' > foo.txt
		sl add foo.txt
		sl commit -m lol
		sl paths --add default ssh://git@github.com/testuser/testrepo.git
	}
	setup_e2e_test
	nvim -u NONE foo.txt +"source $PLUGIN_PATH" +2 +"OpenRemoteTestE2e2"
}

function test_visual_select_range() {
	printf "\ntest_visual_select_range\n"
	function setup_e2e_test(){
		local tmp_dir=$(mktemp -d)
		echo "running in: $tmp_dir"
		cd $tmp_dir
		sl init --git .
		printf 'hello\nworld\ndufus\nfourth' > foo.txt
		sl add foo.txt
		sl commit -m lol
		sl paths --add default ssh://git@github.com/testuser/testrepo.git
		sl debugremotebookmark main .
	}
	setup_e2e_test
	# open file to line 2, select lines 2-3, open remote
	nvim -u NONE foo.txt +"source $PLUGIN_PATH" +2 +'execute "norm Vjj:OpenRemoteTestE2eVisualSelectRange\<CR>"'
}

test() {
	set -x
	test_visual_select_range
	unit_tests
	e2e_test_1
	test_commit_with_multiple_bookmarks
	test_with_repo_thats_not_cwd
	e2e_test_2

	printf "\n\n✅\n"
}
test
